### ISSUE TITLE
Iptables error

### ISSUE THREAD

**Issue by KhalitovAdel** [alekslitvinenk/docker-openvpn#50]
iptables v1.8.3 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.

**Comment by alekslitvinenk** [comment]
Hello. It would help a lot if you provide steps to reproduce the issue. Do you try to lunch docker-openvpn? What is the host operation system? 

Feel free to write to https://gitter.im/docker-openvpn/community to chat

**Comment by alekslitvinenk** [comment]
Didn't find any anomalies
