### ISSUE TITLE
how to create multiple clients 

### ISSUE THREAD

**Issue by ecsuae** [alekslitvinenk/docker-openvpn#77]
hi it is really nice work , can you guide how to create more clients and how to save them

**Comment by alekslitvinenk** [comment]
This is really pleasant to hear. I plan to add possibility to create additional users in the upcoming update. For now you can simply share the same config across multiple users. The server is configured the way it allows multiple users to have the same certificate. Once I implement creating additional users, I’ll turn this flag off or make it optional.

Have a nice day and thank you for your interest!

**Comment by alekslitvinenk** [comment]
Created issue #78 to address this

**Comment by alekslitvinenk** [comment]
Fixed in #78
