### ISSUE TITLE
I got an error AEAD Decrypt error:

### ISSUE THREAD

**Issue by kodermax** [alekslitvinenk/docker-openvpn#85]
After connect I get an error.
```2020-04-01 13:07:42.311999 AEAD Decrypt error: bad packet ID (may be a replay): [ #249 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings```

**Comment by alekslitvinenk** [comment]
Hi! Thank you for your report. I’m looking into it

**Comment by alekslitvinenk** [comment]
Seems like the problem can be worked around by setting different MSS value in client.ovpn file.
https://www.sonassi.com/help/troubleshooting/setting-correct-mtu-for-openvpn
Can you please give me more details on how to reproduce it? Do I need to visit some specific resource after I get connected to VPN?

**Comment by alekslitvinenk** [comment]
New option to set custom MTU will be added in future release in #89
