### ISSUE TITLE
How can i connect OpenVPN by public domain and https?

### ISSUE THREAD

**Issue by Misotech** [alekslitvinenk/docker-openvpn#93]
How can i connect OpenVPN by public domain and https?

**Comment by alekslitvinenk** [comment]
Hi! It shouldn't be a problem to use public domain. Just run docker-openvpn container on machine which has an IP address (a hostname or few can resolve to this IP address). HTTPS isn't supported at the moment as it would require intermediary layer to encrypt/decrypt traffic. We will add such support in future releases
